<a href="https://colab.research.google.com/github/anushkakulk/PracticeML/blob/main/practice/VectorMatrixOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import array
from numpy import trace

v = array([[1], [2], [3]])
print(v, "\n")

u = array([[3], [1], [4]])
print(u, "\n")

A = array([[1,2,3], [3,2,1], [3,1,1]])
print(A, "\n")

print(u.dot(v.T), "\n")
print(v.T.dot(v), "\n")
print(v.T.dot(A).dot(v), "\n")
print(v*u, "\n")
print(trace(A.dot(A.T)), "\n")

[[1]
 [2]
 [3]] 

[[3]
 [1]
 [4]] 

[[1 2 3]
 [3 2 1]
 [3 1 1]] 

[[ 3  6  9]
 [ 1  2  3]
 [ 4  8 12]] 

[[14]] 

[[58]] 

[[ 3]
 [ 2]
 [12]] 

39 



In [ ]:
import numpy as np
from numpy import array
from numpy import trace

x = array([[2], [6]])

y = array([[1], [0]])

X = array([[7, 5], [3, 6]])

Y = array([[2, 4], [1, 0]])

Z = array([[4, -1, 0], [1, 1, 1]])


print((trace(x.dot(x.T))) + x.T.dot(y), "\n")

print(x.T.dot(y), "\n")

print(Y*X, "\n")

print(2*X + 2*Y + X.T.dot(Y), "\n")

print(trace(Y.dot(Y.T)), "\n")

print(Z.dot(Z.T).dot(x), "\n")

[[42]] 

[[2]] 

[[14 20]
 [ 3  0]] 

[[35 46]
 [24 32]] 

21 

[[52]
 [24]] 



In [ ]:
import numpy as np
from numpy import array
from numpy import trace

x = array([[2], [2], [6]])

y = array([[1], [0]])

X = array([[-4, 7, 5], [1, -9, 2], [8, 3, 6]])

Y = array([[2, 4, 6], [1, 0, 13], [-4, 5, 5]])

Z = array([[4, -1, 0], [1, 1, 1]])


print(2*X + 2*Y + X.T.dot(Y))
print(X.T.dot(Y))
print(Y.dot(Z.T))
print(Z.T.dot(Z).dot(x))


[[-43  46  51]
 [ -3  25 -30]
 [ -4  66 108]]
[[-39  24  29]
 [ -7  43 -60]
 [-12  50  86]]
[[  4  12]
 [  4  14]
 [-21   6]]
[[34]
 [ 4]
 [10]]


In [29]:
import numpy as np
from numpy import array
from numpy import trace



X = array([[1,7], [-8,6], [3,1]])

Y = array([[0, 4, 6, -8], [1, -3, 5, 7], [11, 13, 9, 9], [-1, 0, 8, 7]])

Z = array([[0, 4, 8, 1], [-3, 5, 17, 11]])

A = array([[1, 17], [2, 14]])

b = array([[19, -11, 13]])

c = array([[12], [-11], [10]])

x = array([[1], [2], [3]])

y = array([[3, 3, 1]])

print(((x.dot(y)).dot(y.T)).dot(x.T), "\n")



print(3*c - 9, "\n")



print((trace(A.dot(A.T)))*(A), "\n")



print(2*X.dot(Z), "\n")



print((b.dot(c))*(A), "\n")



print(b.dot(X).dot(A), "\n")



print(c*x, "\n")



print(b*y, "\n")



print(c.dot(x.T), "\n")



print(Y.dot(Z.T), "\n")

[[ 19  38  57]
 [ 38  76 114]
 [ 57 114 171]] 

[[ 27]
 [-42]
 [ 21]] 

[[ 490 8330]
 [ 980 6860]] 

[[-42  78 254 156]
 [-36  -4  76 116]
 [ -6  34  82  28]] 

[[ 479 8143]
 [ 958 6706]] 

[[ 306 3602]] 

[[ 12]
 [-22]
 [ 30]] 

[[ 57 -33  13]] 

[[ 12  24  36]
 [-11 -22 -33]
 [ 10  20  30]] 

[[ 56  34]
 [ 35 144]
 [133 284]
 [ 71 216]] 



In [38]:
import numpy as np
from numpy import array
from numpy import trace


# create two matrices and two vectors
X = array([[2,3], [9,1]])
Y = array([[1,0], [2,1]])
x = array([[1], [3]])
y = array([[2], [4]])

# extract 1st col of X
print(X[:,0], "\n")

# extract 2nd row of Y
print(Y[1,:], "\n")

# extract bottom right val of X
print(Y[1,1], "\n")

# adds X + Y
print(X + Y, "\n")

# performs X + XY
print(X + X.dot(Y), "\n")

# hadamard product x ⊙ y
print(x*y, "\n")

# outer product x ⊗ y
print(x.dot(y.T), "\n")

# dot product XY
print(X.dot(Y), "\n")

# inner product ⟨X, Y⟩
print(trace(X.dot(Y.T)), "\n")

[2 9] 

[2 1] 

1 

[[ 3  3]
 [11  2]] 

[[10  6]
 [20  2]] 

[[ 2]
 [12]] 

[[ 2  4]
 [ 6 12]] 

[[ 8  3]
 [11  1]] 

21 



In [61]:
import numpy as np

v = array([[5], [0], [0]])
w = array([[8], [1], [1]])
x = array([[3], [1], [2]])
y = array([[2], [1], [0], [3]])
z = array([[2], [5]])

# vector v norms
print("vector v norms: ",
      np.linalg.norm(v, ord = 1), "  ",
     "%.3f" % np.linalg.norm(v, ord=2), " ",
      np.linalg.norm(v, ord = np.inf))

# vector w norms
print("vector w norms: ",
      np.linalg.norm(w, ord = 1), " ",
      "%.3f" %np.linalg.norm(w, ord = 2), " ",
      np.linalg.norm(w, ord = np.inf))

# vector x norms
print("vector x norms: ",
      np.linalg.norm(x, ord = 1), "  ",
      "%.3f" %np.linalg.norm(x, ord = 2), " ",
      np.linalg.norm(x, ord = np.inf))

# vector y norms
print("vector y norms: ",
      np.linalg.norm(y, ord = 1), "  ",
      "%.3f" %np.linalg.norm(y, ord = 2), " ",
      np.linalg.norm(y, ord = np.inf))

# vector z norms
print("vector z norms: ",
      np.linalg.norm(z, ord = 1), "  ",
      "%.3f" %np.linalg.norm(z, ord = 2), " ",
      np.linalg.norm(z, ord = np.inf))



vector v norms:  5.0    5.000   5.0
vector w norms:  10.0   8.124   8.0
vector x norms:  6.0    3.742   3.0
vector y norms:  6.0    3.742   3.0
vector z norms:  7.0    5.385   5.0
