<a href="https://colab.research.google.com/github/anushkakulk/PracticeML/blob/main/practice/VectorMatrixOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import array
from numpy import trace

v = array([[1], [2], [3]])
print(v, "\n")

u = array([[3], [1], [4]])
print(u, "\n")

A = array([[1,2,3], [3,2,1], [3,1,1]])
print(A, "\n")

print(u.dot(v.T), "\n")
print(v.T.dot(v), "\n")
print(v.T.dot(A).dot(v), "\n")
print(v*u, "\n")
print(trace(A.dot(A.T)), "\n")

[[1]
 [2]
 [3]] 

[[3]
 [1]
 [4]] 

[[1 2 3]
 [3 2 1]
 [3 1 1]] 

[[ 3  6  9]
 [ 1  2  3]
 [ 4  8 12]] 

[[14]] 

[[58]] 

[[ 3]
 [ 2]
 [12]] 

39 



In [ ]:
import numpy as np
from numpy import array
from numpy import trace

x = array([[2], [6]])

y = array([[1], [0]])

X = array([[7, 5], [3, 6]])

Y = array([[2, 4], [1, 0]])

Z = array([[4, -1, 0], [1, 1, 1]])


print((trace(x.dot(x.T))) + x.T.dot(y), "\n")

print(x.T.dot(y), "\n")

print(Y*X, "\n")

print(2*X + 2*Y + X.T.dot(Y), "\n")

print(trace(Y.dot(Y.T)), "\n")

print(Z.dot(Z.T).dot(x), "\n")

[[42]] 

[[2]] 

[[14 20]
 [ 3  0]] 

[[35 46]
 [24 32]] 

21 

[[52]
 [24]] 



In [ ]:
import numpy as np
from numpy import array
from numpy import trace

x = array([[2], [2], [6]])

y = array([[1], [0]])

X = array([[-4, 7, 5], [1, -9, 2], [8, 3, 6]])

Y = array([[2, 4, 6], [1, 0, 13], [-4, 5, 5]])

Z = array([[4, -1, 0], [1, 1, 1]])


print(2*X + 2*Y + X.T.dot(Y))
print(X.T.dot(Y))
print(Y.dot(Z.T))
print(Z.T.dot(Z).dot(x))


[[-43  46  51]
 [ -3  25 -30]
 [ -4  66 108]]
[[-39  24  29]
 [ -7  43 -60]
 [-12  50  86]]
[[  4  12]
 [  4  14]
 [-21   6]]
[[34]
 [ 4]
 [10]]


In [ ]:
import numpy as np
from numpy import array
from numpy import trace



X = array([[1,7], [-8,6], [3,1]])

Y = array([[0, 4, 6, ], [1, 0, 13], [-4, 5, 5]])

Z = array([[4, -1, 0], [1, 1, 1]])
