In [44]:
import numpy as np
from numpy import genfromtxt

A = genfromtxt('test_A.csv', delimiter=',')
B = genfromtxt('test_B.csv', delimiter=',')
C = genfromtxt('test_C.csv', delimiter=',')
x = np.reshape(genfromtxt('test_x.csv', delimiter=','),  (-1,1))

y = np.reshape(genfromtxt('test_y.csv', delimiter=','),  (-1,1))
z = np.reshape(genfromtxt('test_z.csv', delimiter=','),  (-1,1))


print(np.trace(A.dot(A.T)), "\n")
print(np.trace(A*(B)), "\n")
print(np.trace(x.dot(y.T)), "\n")
print(A.dot(B.T), "\n")
print(A.dot(B.T).dot(C).dot(x), "\n")
print(C.dot(x+y))

# vector x norms
print("vector x norms: ",
      np.count_nonzero(x), "  ",
      np.linalg.norm(x, ord = 1), "  ",
      "%.3f" %np.linalg.norm(x, ord = 2), " ",
      np.linalg.norm(x, ord = np.inf))

# vector y norms
print("vector y norms: ",
      np.count_nonzero(y), "  ",
      np.linalg.norm(y, ord = 1), "  ",
      "%.3f" %np.linalg.norm(y, ord = 2), " ",
      np.linalg.norm(y, ord = np.inf))

# vector z norms
print("vector z norms: ",
      np.count_nonzero(z), "  ",
      np.linalg.norm(z, ord = 1), "  ",
      "%.3f" %np.linalg.norm(z, ord = 2), " ",
      np.linalg.norm(z, ord = np.inf))


25.0 

2.0 

2.0 

[[4. 6. 2. 2. 4. 3.]
 [2. 4. 6. 6. 2. 1.]
 [6. 9. 6. 6. 6. 4.]
 [0. 1. 2. 2. 0. 0.]
 [5. 6. 4. 4. 5. 3.]
 [0. 0. 0. 0. 0. 0.]] 

[[ 62.]
 [ 82.]
 [122.]
 [ 22.]
 [ 88.]
 [  0.]] 

[[ 7.]
 [ 8.]
 [14.]
 [ 9.]
 [ 7.]
 [ 9.]]
vector x norms:  2    3.0    2.236   2.0
vector y norms:  3    5.0    3.000   2.0
vector z norms:  2    3.0    2.236   2.0
