In [4]:
import autograd.numpy as np
from autograd import grad
from autograd.numpy import log
from scipy.integrate import quad
import scipy.linalg as linalg
import math

n = 2
A = np.random.random((n,n))
w = np.random.random((n,1))
y = np.random.random((n,1))
x = np.random.random((n,1))

# 1) linear 
def linear(x, y):
    return np.dot(np.transpose(y),x) + np.dot(np.transpose(x), (np.array([[1],[1]])))
grad_foo1 = grad(linear)
print("linear function: autogen grad: \n", grad_foo1(x, y))
print("linear function: theoret grad: \n", y + (np.array([[1],[1]])), "\n")

# 2) quadratic
def quad(x, A):
    return np.dot(np.dot(np.transpose(x), A), x)
grad_foo2 = grad(quad)
print("quad function: autogen grad: \n", grad_foo2(w, A))
print("quad function: theoret grad: \n", np.dot((np.transpose(A) + A), w), "\n")

#3) trace of quadratic
def trace_quad(x, A):
    return np.trace(np.dot(np.dot(np.transpose(x), A), x))
grad_foo3 = grad(trace_quad)
print("trace of quad function: autogen grad: \n", grad_foo3(w, A))
print("trace of quad function: theoret grad: \n", np.dot((np.transpose(A) + A), w), "\n")

# 4) activation function / ReLU
def relu(w, x):
    v = np.dot(np.transpose(w), x)
    return np.maximum(0, v)
def grad_relu(w,x):
    if w.T.dot(x) > 0:
        return x
    else:
        return 0
grad_foo4 = grad(relu)
print("relu function: autogen grad: \n", grad_foo4(w, x))
print("relu function: theoret grad: \n", grad_relu(w,x), "\n")

# 5) linear regression 
def linreg(w, x, y):
    total_sum = 0
    for i in range(n):
        before_sqr = (np.dot(w.T, x[i]) - y[i])
        total_sum += np.dot(before_sqr, before_sqr)
    return .5 * total_sum
def grad_linreg(w, x, y):
    total_sum = 0
    for i in range(n):
        total_sum += (np.dot(w.T, x[i, :]) - y[i]) * x[i,]
    return total_sum
grad_foo5 = grad(linreg)
print("linear regression function: autogen grad: \n", grad_foo5(w, A, y))
print("linear regression function: theoret grad: \n", np.reshape(grad_linreg(w, A ,y), (-1, 1)), "\n")

# 6) multivariate gaussian trace
def trace_mult_gaus(x, A):
  return pow(math.e, -np.trace(np.dot(np.dot(np.transpose(x), A), x)))
def grad_trace_mult_gaus(x, A):
    return -1 * pow(math.e, -(np.dot(np.dot(np.transpose(x), A), x))) * np.dot((np.transpose(A) + A), x)
grad_foo6 = grad(trace_mult_gaus)
print("multivariate gaussian trace function: autogen grad: \n", grad_foo6(x,A))
print("multivariate gaussian trace function: theoret grad: \n", grad_trace_mult_gaus(x,A), "\n")

# 7) multivariate gaussian
def mult_gaus(x, A):
  return pow(math.e, -(np.dot(np.dot(np.transpose(x), A), x)))
def grad_mult_gaus(x, A):
    return -1 * pow(math.e, -(np.dot(np.dot(np.transpose(x), A), x))) * np.dot((np.transpose(A) + A), x)
grad_foo7 = grad(mult_gaus)
print("multivariate gaussian function: autogen grad: \n", grad_foo7(x,A))
print("multivariate gaussian function: theoret grad: \n", grad_mult_gaus(x,A), "\n")

# 8) sigmoid function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def grad_sigmoid(x):
    return sigmoid(x) * (1 - sigmoid(x))
grad_foo8 = grad(sigmoid)
print("sigmoid function: autogen grad: \n", grad_foo8(x[1,:]))
print("sigmoid function: theoret grad: \n", grad_sigmoid(x[1,:]), "\n")

# 9) logistic regression objective function
def log_reg_obj(w, x):
    return 1 / (1 + pow(math.e, (-np.dot(w.T, x))))
def grad_log_reg_obj(w, x):
    return (x * pow(math.e, (-np.dot(w.T, x)))) / ((1 + pow(math.e, (-np.dot(w.T, x))))**2)
grad_foo9 = grad(log_reg_obj)
print("logistic regression objective: autogen grad: \n", grad_foo9(w, x))
print("logistic regression objective: theoret grad: \n", grad_log_reg_obj(w,x), "\n")

# 10) L1 norm
def l1(x):
    return np.sum(np.abs(x))
def grad_l1(x):
    sign = np.zeros_like(x)
    for i in range(n):
        if x[i, 0] > 0:
            sign[i, 0] = 1
        else:
            sign[i, 0] = -1
    return sign
grad_foo10 = grad(l1)
print("L1 Norm: autogen grad: \n", grad_foo10(x))
print("L1 Norm: theoret grad: \n", grad_l1(x), "\n")

# 11) L2 norm
def l2(x):
    sum_squared = 0
    for i in range(n):
        sum_squared += x[i, 0]**2
    return np.sqrt(sum_squared)
def grad_l2(x):
    return x / l2(x)
grad_foo11 = grad(l2)
print("L2 Norm: autogen grad: \n", grad_foo11(x))
print("L2 Norm: theoret grad: \n", grad_l2(x), "\n")

# 12) SVM objective : SKIP

# 13) PCA objective
lam = np.random.random()
def pca(x, A):
    return np.dot(np.dot(np.transpose(x), A), x) - lam * (np.dot(np.dot(np.transpose(x), np.identity(n)), x) - 1)
grad_foo13 = grad(pca)
print("pca objective: autogen grad: \n", grad_foo13(x, A))
print("pca objective: theoret grad: \n", np.dot((np.transpose(A) + A), x) - 2 * lam * x, "\n")

# 14) gaussian maximum likelihood
mu = np.random.random()
sig = np.random.random()
def gauss_max(mu, sig, x):
    n = len(x)
    prod = 1
    for i in range(n):
        prod *= (1 / (sig * np.sqrt(2 * np.pi))) * (np.exp(-np.linalg.norm(x[i] - mu)**2 / (2 * sig**2)))
    return np.log(prod)
def grad_gauss_max(mu, sig, x):
    n = len(x)
    sum = 0
    for i in range(n):
        sum += (x[i] - mu) 
    return sum / sig**2
grad_foo14 = grad(gauss_max)
print("gaussian maximum likelihood: autogen grad: \n", grad_foo14(mu, sig, x))
print("gaussian maximum likelihood: theoret grad: \n", np.sum(grad_gauss_max(mu, sig, x)), "\n")

# 15) exponential maximum likelihood
def exp_max(lam, x):
    n = len(x)
    prod = 1
    for i in range(n):
         prod *= lam * np.exp(-lam * x[i, :])
    return np.log(prod)
def grad_exp_max(lam, x):
    n = len(x)
    sum = 0
    for i in range(n):
        sum += (1/lam) - x[i, :]
    return sum
grad_foo15 = grad(exp_max)
print("exponential maximum likelihood: autogen grad: \n", grad_foo15(lam, x))
print("exponential maximum likelihood: theoret grad: \n", grad_exp_max(lam,x), "\n")

# 16) bernoulli maximum likelihood
p = np.random.random()
a = np.random.uniform(0,1)
def bern_max(p, a):
    prod = 1
    for i in range(n):
        prod *= pow(p, a) * pow(1 - p, 1 - a)
    return np.log(prod)
def grad_bern_max(p, a):
    sum = 0
    for i in range(n):
        sum += (a/p) - ((1 - a) / (1 - p))
    return sum
grad_foo16 = grad(bern_max)
print("bernoulli maximum likelihood: autogen grad: \n", grad_foo16(p, a))
print("bernoulli maximum likelihood: theoret grad: \n", grad_bern_max(p, a), "\n")

# 17) uniform maximum likelihood
a = np.random.uniform(0, 1)
b = np.random.uniform(a, 1)
def unif_max(a,b):
    prod = 1
    for i in range(n):
         prod *= 1 / (b - a)
    return np.log(prod)
def grad_unif_max(a, b):
    return n / (b - a)
grad_foo17 = grad(unif_max)
print("uniform maximum likelihood: autogen grad: \n", grad_foo17(a, b))
print("uniform maximum likelihood: theoret grad: \n", grad_unif_max(a,b), "\n")



linear function: autogen grad: 
 [[1.1208656 ]
 [1.02069091]]
linear function: theoret grad: 
 [[1.1208656 ]
 [1.02069091]] 

quad function: autogen grad: 
 [[1.59550058]
 [1.2319578 ]]
quad function: theoret grad: 
 [[1.59550058]
 [1.2319578 ]] 

trace of quad function: autogen grad: 
 [[1.59550058]
 [1.2319578 ]]
trace of quad function: theoret grad: 
 [[1.59550058]
 [1.2319578 ]] 

relu function: autogen grad: 
 [[0.14006323]
 [0.25695632]]
relu function: theoret grad: 
 [[0.14006323]
 [0.25695632]] 

linear regression function: autogen grad: 
 [[0.73947777]
 [0.60500212]]
linear regression function: theoret grad: 
 [[0.73947777]
 [0.60500212]] 

multivariate gaussian trace function: autogen grad: 
 [[-0.3878101 ]
 [-0.29915619]]
multivariate gaussian trace function: theoret grad: 
 [[-0.3878101 ]
 [-0.29915619]] 

multivariate gaussian function: autogen grad: 
 [[-0.3878101 ]
 [-0.29915619]]
multivariate gaussian function: theoret grad: 
 [[-0.3878101 ]
 [-0.29915619]] 

sigmoid fu